services:
  nacos-service-switcher:
    build: .
    image: nacos-service-switcher:latest
    ports:
      - "5000:5000"
    environment:
      - NACOS_SERVER=http://your-nacos-server:8848
      - NACOS_NAMESPACE=your-namespace
      - NACOS_USERNAME=your-username
      - NACOS_PASSWORD=your-password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
